CREATE TABLE MEMBER(
    MEMBER_NO    NUMBER       PRIMARY KEY,
    MEMBER_NAME  VARCHAR2(20) NOT NULL,
    AGE          NUMBER,
    GENDER       CHAR(1)      CHECK(GENDER IN ('M','F')),
    ENROLL_DATE  DATE         DEFAULT SYSDATE
);
--INSERT
--INSERT INTO 테이블명 VALUES(컬럼 순서대로 값 대입)
INSERT INTO MEMBER VALUES(1,'이름1',20,'F',SYSDATE);
INSERT INTO MEMBER VALUES(2,'이름2',21,'M',SYSDATE);
INSERT INTO MEMBER VALUES(3,'이름3',22,'M',DEFAULT);

--INSERT INTO 테이블명 (컬럼명1,컬럼명2 ...)VALUES(값1,값2 ...)
INSERT INTO MEMBER(MEMBER_NO,MEMBER_NAME,AGE,GENDER,ENROLL_DATE)VALUES(4,'이름',23,'F',SYSDATE);
INSERT INTO MEMBER(GENDER,ENROLL_DATE,MEMBER_NAME,AGE,MEMBER_NO)VALUES('M',SYSDATE,'이름5',24,5);
INSERT INTO MEMBER(MEMBER_NO,MEMBER_NAME,GENDER)VALUES(6,'이름6','F');

SELECT * FROM MEMBER;
--UPDATE
--UPDATE 테이블명 SET 변경할 컬럼이름 = 변경할 값, 병경할 컬럼이름 = 변경할 값 VALUE 변경할 ROW선택구문
UPDATE MEMBER SET AGE = 25 WHERE MEMBER_NO=6;
--WHERE 을 빼서 모두 33으로 업데이트됨.
UPDATE MEMBER SET AGE = 33;

UPDATE MEMBER SET MEMBER_NAME='이름55',AGE=55,GENDER='F' WHERE MEMBER_NO=5;
UPDATE MEMBER SET AGE=10 WHERE GENDER='M';
UPDATE MEMBER SET AGE=13 WHERE GENDER='M' AND MEMBER_NAME='이름3';

--DELETE
--DELETE FROM 테이블명 WHERE 삭제할 ROE 선택구문
DELETE FROM MEMBER WHERE MEMBER_NO =5;
DELETE FROM MEMBER WHERE GENDER ='M';
DELETE FROM MEMBER;


COMMIT;

DELETE FROM MEMBER;
ROLLBACK;
TRUNCATE TABLE MEMBER;
